/*
	Static_Data table_name `paragraph`
*/
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (1,1,'Голова СО університету','10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (2,1,'Заступники голови СО університету','8.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (3,1,'Секретар СО університету, керівники відділів СО університету, керівники клубів за інтересами','6.25');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (4,1,'Голови СО на факультеті (ННІ)','6.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (5,1,'Члени Вченої ради Університету','4.70');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (6,1,'Заступники голови СО на факультеті (ННІ)','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (7,1,'Керівники відділів СО на факультеті (ННІ)','3.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (8,1,'Секретар СО факультету (ННІ)','3.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (9,1,'Старости академічних груп','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (10,1,'Член Вченої ради факультету','1.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (11,1,'Члени СО Університету','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (12,1,'Члени СО факультету (ННІ), голова та секретар ЦВК університету','2.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (13,1,'Одноразова участь в організації заходів, що проводить СО Університету*, член ЦВК університету','0.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (14,1,'Одноразова участь в організації заходів, що проводить СО факультету (ННІ)*','0.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (15,1,'Неявка голови студентської організації (ради) на організаційні збори СО. невиконання ним поставленого СО завдання','-1.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (16,1,'Заступник старости академічної групи **','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (17,1,'Отримання призових місць на фестивалі «Аграрна Республіка» (1 місце)','2.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (18,1,'Отримання призових місць на фестивалі «Аграрна Республіка» (2 місце)','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (19,1,'Отримання призових місць на фестивалі «Аграрна Республіка» (3 місце)','1.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (20,1,'Одноразова допомога студента в організації заходів, що проводить CO Університету*','1.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (21,1,'Одноразова допомога студента в організації заходів, що проводить CO факультету (ННІ)*','0.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (22,1,'Член ЦВК по виборах голови студентської організації університету','0.90');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (23,1,'Голова та секретар ЦВК по виборах голови студентськоїорганізації університету','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (24,1,'Створення Положення одноосібно','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (25,1,'Створення Положення в співавторстві','0.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (26,1,'Редакція існуючого Положення ','0.50');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (27,2,'Голова об’єднаної студентської ради гуртожитків ','8.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (28,2,'Голови СР гуртожитків','6.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (29,2,'Заступник голови СР Гуртожитку','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (30,2,'Секретар СР Гуртожитку, керівники відділів СР Гуртожитку','3.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (31,2,'Старости які відповідають за декілька блоків','3.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (32,2,'Старости поверхів (блоків)','2.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (33,2,'Члени СР гуртожитку','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (34,2,'Заступник старости поверхів','1.10');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (35,2,'Комісія при поселенні в гуртожиток','0.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (36,2,'Одноразова допомога в організації заходів, що проводить СР Гуртожитків*','0.50');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (37,3,'Голова профбюро факультету (ННІ)','5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (38,3,'Заступник голови профбюро факультету (ННІ)','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (39,3,'Секретар голови Профбюро (ННІ)','3.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (40,3,'Керівники відділів Профбюро','2.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (41,3,'Профорг групи','1.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (42,3,'Одноразова допомога в організації заходів, що проводить Профбюро факультетів (ННІ)*','0.25');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (43,4,'Членство у волонтерському зареєстрованому об`єднанні','4.25');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (44,4,'Курсант автошколи НУБіП України','3.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (45,4,'Участь в акції "День донора" в НУБіП України','3.15');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (46,4,'Членство у громадському формуванні "Університетська варта"','2.30');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (47,4,'Одноразова участь у заходах, що проводить соціальний відділ СО НУБіП України*','0.25');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (48,4,'Одноразова участь у заходах, що проводить соціальний відділ на факультетах (ННІ)*','0.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (49,4,'Одноразова участь у благоустрої території Голосіївського району*','0.40');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (50,4,'Участь заходах на факультеті (ННІ), в університеті, облаштування гуртожитку та прилеглої території*','0.40');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (51,4,'Вчинення порушення, що передбачає дисциплінарне стягнення у вигляді зауваження, догани, не поселення в гуртожиток з наступного навчального року, розірвання договору найму на проживання. Свідоме ігнорування та невиконання розпоряджень керівництва факультету (ННІ), університету. Свідоме розміщення недостовірної інформації щодо отриманих балів.','-10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (52,4,'За відмову від участі у змаганнях в складі збірної команди НУБіП України за кожний тур, гру, зустріч – за поданням викладачів кафедри фізичного виховання відповідальних за підготовку збірних команд університету з видів спорту і списків збірних команд університету затверджених проректором університету.','-5.00');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (53,5,'Переможці і призери міжнародних олімпіад','10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (54,5,'Переможці ІІ етапу Всеукраїнських студентських олімпіад (1 місце)','10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (55,5,'Переможці ІІ етапу Всеукраїнських студентських олімпіад (2 місце)','9.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (56,5,'Переможці ІІ етапу Всеукраїнських студентських олімпіад (3 місце)','9.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (57,5,'Отримання студентом патенту на винахід (корисну модель) (одноосібно)','10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (58,5,'Отримання студентом патенту на винахід (корисну модель) (успівавторстві з НПП)','7.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (59,5,'Переможці І етапу студентської Всеукраїнської олімпіади (1 місце)','7.25');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (60,5,'Переможці І етапу студентської Всеукраїнської олімпіади (2 місце)','6.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (61,5,'Переможці І етапу студентської Всеукраїнської олімпіади (3 місце)','6.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (62,5,'Призери ІІ етапу Всеукраїнських студентських олімпіад (1 місце)','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (63,5,'Призери ІІ етапу Всеукраїнських студентських олімпіад (2 місце)','3.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (64,5,'Призери ІІ етапу Всеукраїнських студентських олімпіад (3 місце)','3.25');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (65,5,'Учасник ІІ етапу Всеукраїнських студентських олімпіад','2.90');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (66,5,'Участь в олімпіадах Університетського рівня','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (67,5,'Публікація статті (одноосібно)','8.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (68,5,'Публікація статті (із співавторством НПП)','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (69,5,'Публікація статті (із співавторством із студентами на кожного)','2.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (70,5,'Кращий читач наукової бібліотеки (1 місце)','2.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (71,5,'Кращий читач наукової бібліотеки (2 місце)','1.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (72,5,'Кращий читач наукової бібліотеки (3 місце)','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (73,5,'Публікація тез конференції (одноосібно)','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (74,5,'Публікація тез конференції (у співпраці з НПП)','2.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (75,5,'Публікація тез конференції (із співавторством із студентами)','1.50');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (76,6,'Виступ на конференціях що проходять за межами території України (на іноземній мові)','7.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (77,6,'Виступ на конференціях, що проходять в Україні','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (78,6,'Виступ на конференціях на рівні Університету','2.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (79,6,'Участь на конференціях, що проходять за межами території України (на іноземній мові)','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (80,6,'Участь на конференціях що проходить на рівні України','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (81,6,'Участь на конференціях на рівні Університету','0.50');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (82,7,'Перемога в Інтелектуальних битвах між академічними групами','5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (83,7,'2 місце в Інтелектуальних битвах між академічними групами','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (84,7,'3 місце в Інтелектуальних битвах між академічними групами','3.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (85,7,'Зайняте 4 місце в Інтелектуальних битвах між академічними групами','6.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (86,7,'Зайняте 5 місце в Інтелектуальних битвах між академічними групами','6.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (87,7,'Зайняте 6 місце в Інтелектуальних битвах між академічними групами','5.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (88,7,'Зайняте 7 місце в Інтелектуальних битвах між академічними групами','5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (89,7,'Зайняте 8 місце в Інтелектуальних битвах між академічними групами','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (90,7,'Зайняте 9-11 місце в Інтелектуальних битвах між академічними групами','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (91,7,'Перемога в "Агродебатах" "Агро-2019" "Нове зернятко" та заходів клубу за інтересами*','8.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (92,7,'2 місце в "Агродебатах" "Агро-2019" "Нове зернятко" та заходів клубу за інтересами*','7.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (93,7,'3 місце в "Агродебатах" "Агро-2019" "Нове зернятко" та заходів клубу за інтересами*','7.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (94,7,'Участь у ректорському проекті «Школа лідера НУБіП України»','1.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (95,7,'Отримання сертифікату учасника у ректорському проекті «Школа лідера НУБіП України»','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (96,7,'Розробка проектів у рамках ректорської «Школи лідера НУБіП України»','10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (97,7,'Участь у заходах що проводять клуби за інтересами*','0.40');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (98,7,'Участь в інтелектуальних конкурсах на рівні університету*','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (99,7,'Участь в інтелектуальних конкурсах на рівні факультету (ННІ) *','1.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (100,7,'Участь у інтелектуальних конкурсах нарівні гуртожитку*','0.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (101,7,'Вчинення порушення, що передбачає дисциплінарне стягнення увигляді зауваження, догани, не поселення в гуртожиток знаступного навчального року, розірвання договору найму напроживання. Свідоме ігнорування та невиконання розпоряджень керівництва факультету (ННІ), університету. Свідоме розміщення недостовірної інформації щодо отриманих балів','-10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (102,7,'За відмову від участі у змаганнях в складі збірної команди НУБіП України за кожний тур, гру, зустріч–за поданням викладачів кафедри фізичного виховання відповідальних за підготовку збірних командуніверситету з видів спорту і списків збірних командуніверситету затверджених проректором університету','-5.00');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (103,8,'Абітурієнта до участі в олімпіаді','3.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (104,8,'Слухача підготовчих курсів Університету','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (105,8,'Абітурієнта до вступу на бакалаврат 1 студент','7.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (106,8,'Абітурієнта до вступу на бакалаврат 3 (та більше) студента','10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (107,8,'Абітурієнта з іншого ЗВО до вступу в магістратуру','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (108,8,'Профорієнтаційна робота в школах з результатами (анкета абітурієнта, фото, публікація на сайті ','1.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (109,8,'Член команди Університету з профорієнтаційної роботи','3.50');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (110,9,'Капітан збірної команди України, МОН, Києва','10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (111,9,'Капітан збірної Університету','8.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (112,9,'Член І збірної Університету (Бере участь в 65-70% змагань)','6.25');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (113,9,'Член ІІ збірної Університету (Бере участь в 65-70% змагань)','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (114,9,'Керівник університетської варти','7.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (115,9,'Член університетської варти (за поданням керівника)','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (116,9,'Капітан збірної факультету (ННІ)','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (117,9,'Член збірної факультету (ННІ) (Бере участь в 65-70% змагань)','3.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (118,9,'Студент, курсант кафедри військової підготовки','2.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (119,9,'Капітан збірної гуртожитку','3.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (120,9,'Член збірної гуртожитку (Бере участь в 65-70% змагань)','2.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (121,9,'Член спортивної секції (за умови реєстрації і відвідування не менше 50%)','1.75');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (122,10,'Перемога збірної університету на рівні України м. Києва','6.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (123,10,'2 місце збірної університету на рівні України м. Києва','5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (124,10,'3 місце збірної університету на рівні України м. Києва','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (125,10,'Перемога збірної факультету на змагання що проводяться на рівні Університету','5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (126,10,'2 місце збірної факультету на змагання що проводяться на рівні Університету','3.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (127,10,'3 місце збірної факультету на змагання що проводяться на рівні Університету','2.80');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (128,10,'Перемога збірної гуртожитку на рівні гуртожитків','3.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (129,10,'2 місце збірної гуртожитку на рівні гуртожитків','2.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (130,10,'3 місце збірної гуртожитку на рівні гуртожитків','1.80');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (131,11,'Перемога в змаганні найспортивніша академічна група','5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (132,11,'2 місце в змаганні найспортивніша академічна група','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (133,11,'3 місце в змаганні найспортивніша академічна група','3.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (134,11,'4 місце в змаганні найспортивніша академічна група','3.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (135,11,'5 місце в змаганні найспортивніша академічна група','3.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (136,11,'6 місце в змаганні найспортивніша академічна група','3.25');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (137,11,'7 місце в змаганні найспортивніша академічна група','3.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (138,11,'8 місце в змаганні найспортивніша академічна група','2.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (139,11,'9-11 місце в змаганні найспортивніша академічна група','2.20');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (140,11,'Перемога в спортивних заходах що проводить СО, СР, кафедра ФП*','3.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (141,11,'2 місце в спортивних заходах що проводить СО, СР, кафедра ФП*','2.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (142,11,'3 місце в спортивних заходах що проводить СО, СР, кафедра ФП*','1.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (143,11,'Учасник спортивних заходів що проводить СО, СР, кафедра ФП*','0.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (144,11,'Участь в спортивних заходах на рівні університету*','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (145,11,'Участь в спортивних заходах на рівні факультету (ННІ)','1.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (146,11,'Участь у спортивних заходах на рівні гуртожитку*','0.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (147,11,'Організоване вболівання за збірну Університету (факультету)*','0.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (148,11,'Вчинення порушення, що передбачає дисциплінарне стягнення увигляді зауваження, догани, не поселення в гуртожиток знаступного навчального року, розірвання договору найму на проживання. Свідоме ігнорування та невиконання розпоряджень керівництва факультету (ННІ), університету. Свідоме розміщення недостовірної інформації щодо отриманих балів','-10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (149,11,'За відмову від участі у змаганнях в складі збірної команди НУБіП України за кожний тур, гру, зустріч – за поданням викладачів кафедри фізичного виховання відповідальних за підготовку збірних команд університету з видів спорту і списків збірних команд університету затверджених проректором університету','-5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (150,11,'За відмову студента від участі у змаганнях у складі збірної команди факультету за кожний тур, гру, зустріч - за поданням голови СО факультету','-1.00');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (151,12,'Капітан команди фанатського руху Університету','5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (152,12,'Учасник команди фанатського руху Університету (відвідує не менше 75% заходів)','2.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (153,12,'Організоване вболівання за збірну Університету (факультету/ ННІ)*','0.20');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (154,13,'Капітан збірної Університету з кіберспортивної дисципліни','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (155,13,'Член збірної Університету з кіберспортивної дисципліни','2.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (156,13,'Капітан збірної факультету (ННІ) з кіберспортивної дисципліни','3.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (157,13,'Учасник збірної факультету (ННІ) з кіберспортивної дисципліни','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (158,13,'Перемога збірної Університету з кіберспортивної дисципліни на рівні України або м. Києва','5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (159,13,'2 місце збірної Університету з кіберспортивної дисципліни на рівні України або м. Києва','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (160,13,'3 місце збірної Університету з кіберспортивної дисципліни на рівні України або м. Києва','3.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (161,13,'Перемога збірної факультету (ННІ) з кіберспортивної дисципліни на рівні Університету','2.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (162,13,'2 місце збірної факультету (ННІ) з кіберспортивної дисципліни на рівні Університету','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (163,13,'3 місце збірної факультету (ННІ) з кіберспортивної дисципліни на рівні Університету','1.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (164,13,'Участь у кіберспортивному турнірі на рівні Університету *','0.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (165,13,'Участь у кіберспортивному турнірі на рівні факультету (ННІ) *','0.20');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (166,14,'Учасник основного складу народного колективу (Бере участь в 75 %заходів)','10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (167,14,'Учасник основного складу художнього колективу (Бере участь в 75 %заходів)','8.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (168,14,'Учасник збірної команди КВН Університету','4.25');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (169,14,'Учасник збірної команди КВН факультету (ННІ)','3.25');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (170,15,'1 місце на міжнародному рівні','8.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (171,15,'2 місце на міжнародному рівні','5.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (172,15,'3 місце на міжнародному рівні','4.25');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (173,15,'Представлення університету на міжнародному рівні','6.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (174,15,'1 місце на Всеукраїнському рівні (ІІ-6,00 ІІІ-5,25)','6.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (175,15,'2 місце на Всеукраїнському рівні (ІІ-6,00 ІІІ-5,25)','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (176,15,'3 місце на Всеукраїнському рівні (ІІ-6,00 ІІІ-5,25)','3.75');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (177,15,'Представлення університету на Всеукраїнському рівні','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (178,15,'Отримання гран-прі в заходах що організовує СО Університету,кафедра культурології (Голосіївська весна)','5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (179,15,'1 місце в заходах що організовує СО Університету, кафедра культурології','3.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (180,15,'2 місце в заходах що організовує СО Університету, кафедра культурології','2.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (181,15,'3 місце в заходах що організовує СО Університету, кафедра культурології','2.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (182,15,'4-10 місце в заходах що організовує СО Університету, кафедра культурології','2.15');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (183,15,'Участь у мистецьких заходах на рівні університету*','1.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (184,15,'Участь у мистецьких заходах на рівні факультету (ННІ)*','1.25');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (185,15,'Участь у мистецьких заходах на рівні гуртожитку*','1.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (186,15,'Написання статті на сайт Університету у публіцистичному стилі *','0.20');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (187,16,'Переможець конкурсу \"Краса НУБіП\"','5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (188,16,'2 місце на конкурсі \"Краса НУБіП\"','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (189,16,'3 місце на конкурсі \"Краса НУБіП\"','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (190,16,'Переможець конкурсу \"Пісенних Баталій\" найспівочішої академічної групи','5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (191,16,'2 місце на конкурсі \"Пісенних Баталій\" найспівочішої академічної групи','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (192,16,'3 місце на конкурсі \"Пісенних Баталій\" найспівочішої академічної групи','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (193,16,'4 місце на конкурсі \"Пісенних Баталій\"','6.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (194,16,'5 місце на конкурсі \"Пісенних Баталій\"','5.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (195,16,'6 місце на конкурсі \"Пісенних Баталій\"','4.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (196,16,'7 місце на конкурсі \"Пісенних Баталій\"','4.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (197,16,'8 місце на конкурсі \"Пісенних Баталій\"','3.50');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (198,16,'9-16 місце на конкурсі \"Пісенних Баталій\"','3.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (199,16,'Учасник конкурсу \"Краса НУБіП\"','3.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (200,16,'Вчинення порушення, що передбачає дисциплінарне стягнення увигляді зауваження, догани, не поселення в гуртожиток з наступного навчального року, розірвання договору найму на проживання.Свідоме ігнорування та невиконання  розпоряджень керівництва факультету (ННІ), університету. Свідоме розміщення недостовірної інформації щодо отриманих балів','-10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (201,16,'За відмову від участі у змаганнях в складі збірної команди НУБіП України за кожний тур, гру, зустріч – за поданням викладачів кафедри фізичного виховання відповідальних за підготовку збірних команд університету з видів спорту і списків збірних команд університету затверджених проректором університету','-5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (202,16,'За відмову студента від участі у заходах у складі команди факультету за кожний тур, захід, зустріч - за поданням голови CO факультету','-1.00');

INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (203,17,'Вчинення порушення, що передбачає дисциплінарне стягнення у вигляді зауваження, догани, не поселення в гуртожиток з наступного навчального року, розірвання договору найму на проживання. Свідоме ігнорування та невиконання розпоряджень керівництва факультету (ННІ), університету. Свідоме розміщення недостовірної інформації щодо отриманих балів','-10.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (204,17,'За відмову від участі у змаганнях в складі збірної команди НУБіП України за кожний тур, гру, зустріч - за поданням викладачів кафедри 2 фізичного виховання відповідальних за підготовку збірних команд','-5.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (205,17,'За відмову студента від участі у заходах у складі команди факультету 3 за кожний тур, захід, зустріч - за поданням голови СО факультету','-1.00');
INSERT INTO `paragraph` (`id_paragraph`,`id_subblock`,`name`,`score`) VALUES (206,17,'Неявка голови студентської організації (ради) на організаційні збори СО; невиконання ним поставленого СО завдання*','-1.00');
